on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache Cargo registry
      uses: actions/cache@v2
      env:
        cache-name: cache-cargo-registry
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-stable-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-stable-cargo-registry-
    - name: Cache Cargo index
      uses: actions/cache@v2
      env:
        cache-name: cache-cargo-index
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-stable-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-stable-cargo-index-
    - name: Install cargo-deb and cargo-generate-rpm
      run: cargo install cargo-deb cargo-generate-rpm
    - name: Build
      run: cargo build --verbose --release
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
